name: Acquire Activation File
on: workflow_dispatch # Dijalankan manual lewat tombol

jobs:
  activation:
    name: Request Manual Activation File
    runs-on: ubuntu-latest
    steps:
      # Request activation file
      - name: Request manual activation file
        id: getManualLicenseFile
        # Gunakan image Unity yang sesuai (2020/2021/2022 bebas, yang penting ada)
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2021.3.15f1 # Sesuaikan atau biarkan default

      # Upload hasil file .alf agar bisa kamu download
      - name: Upload activation file
        uses: actions/upload-artifact@v3
        with:
          name: Unity_v2021.alf
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
