name: Acquire Activation File
on: workflow_dispatch

jobs:
  activation:
    name: Request Manual Activation File
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout Wajib ada supaya Action bisa baca ProjectVersion.txt
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Request File (JANGAN MASUKKAN unityVersion DI SINI)
      # Dia akan otomatis cari file ProjectSettings/ProjectVersion.txt di repo kamu
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2

      # 3. Upload Hasilnya (Pakai v4 biar tidak error)
      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: Unity_Activation_File
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
